name: Go CI

# Trigger workflow on push or pull request to main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      # Step 3: Install dependencies
      - name: Install dependencies
        run: go mod tidy

      # Step 4: Run tests with coverage
      - name: Run tests
        run: go test ./... -v -cover

      # Step 5: Upload test coverage as artifact (optional)
      - name: Upload coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.out
