name: Nodejs Application Deployment
on: 
  push:
    branches:
      - main
jobs: 
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm Install

      - name: Run unit tests
        run: npm test

      - name: Login into docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push the docker image
        uses: docker/docker-push-action@6
        with: 
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest
      
      - name: Deploy on AWS EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            echo "Stopping the old container..."
            docker stop node-app || true
            docker rm node-app || true
            echo "Pulling the new image..."
            docker pull ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest
            echo "Starting new container"
            docker run -d 5000:5000 --name node-app ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest



    
    
